# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{app2engine}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["eregon"]
  s.date = %q{2010-10-03}
  s.default_executable = %q{app2engine}
  s.description = %q{Ease the conversion of a Rails 3 app in an Engine}
  s.email = %q{eregontp@gmail.com}
  s.executables = ["app2engine"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "bin/app2engine",
     "lib/app2engine.rb",
     "lib/app2engine/files/__project__.gemspec",
     "lib/app2engine/files/lib/__project__.rb",
     "lib/app2engine/files/lib/__project__/engine.rb",
     "lib/app2engine/files/lib/generators/__project__/migrations/migrations_generator.rb",
     "lib/app2engine/rake/convert_tasks.rb",
     "lib/app2engine/rake/extra_tasks.rb",
     "lib/app2engine/rake/tasks.rb"
  ]
  s.homepage = %q{http://github.com/eregon/app2engine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Convert a Rails 3 app to an Engine}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 0"])
    else
      s.add_dependency(%q<term-ansicolor>, [">= 0"])
    end
  else
    s.add_dependency(%q<term-ansicolor>, [">= 0"])
  end
end

